import { StyleSheet } from 'react-native';
import { palette } from '../constants';

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: palette.page,
    flex: 1,
  },
  navigatorBar: {
    backgroundColor: palette.panel,
    borderTopColor: palette.faint,
    paddingTop: 0,
  },
  navigatorItem: {
    paddingBottom: 0,
    paddingTop: 2,
  },
  navigatorIconSlot: {
    marginBottom: -3,
    marginTop: 0,
  },
  navigatorLabel: {
    fontSize: 10,
    fontWeight: '900',
  },
  navigatorIcon: {
    fontSize: 14,
    fontWeight: '900',
  },
  tabGlyph: {
    alignItems: 'center',
    borderRadius: 8,
    height: 24,
    justifyContent: 'center',
    width: 30,
  },
  tabGlyphActive: {
    backgroundColor: palette.redSoft,
  },
  content: {
    gap: 16,
    padding: 18,
    paddingBottom: 14,
  },
  header: {
    gap: 16,
    paddingTop: 12,
  },
  logoRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  logoMark: {
    alignItems: 'center',
    backgroundColor: palette.ink,
    borderRadius: 8,
    height: 55,
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    width: 62,
  },
  headerSearchInput: {
    backgroundColor: palette.panel,
    borderColor: palette.faint,
    borderRadius: 8,
    borderWidth: 1,
    color: palette.ink,
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  logoText: {
    color: palette.panel,
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 13,
    textAlign: 'center',
  },
  headerCopy: {
    flex: 1,
  },
  title: {
    color: palette.ink,
    fontSize: 32,
    fontWeight: '900',
    lineHeight: 36,
    marginTop: 3,
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaPill: {
    backgroundColor: palette.panel,
    borderColor: palette.faint,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  metaLabel: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  metaValue: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: '800',
    marginTop: 3,
  },
  screen: {
    gap: 16,
  },
  loadingPanel: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: 200,
  },
  alert: {
    backgroundColor: palette.redSoft,
    borderColor: '#ffd1c5',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  alertTitle: {
    color: palette.red,
    fontSize: 14,
    fontWeight: '900',
  },
  alertText: {
    color: palette.ink,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metricCard: {
    backgroundColor: palette.panel,
    borderColor: palette.faint,
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 116,
    padding: 14,
    width: '48%',
  },
  metricAccent: {
    borderRadius: 2,
    height: 4,
    marginBottom: 14,
    width: 36,
  },
  metricLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  metricValue: {
    color: palette.ink,
    fontSize: 30,
    fontWeight: '900',
    marginTop: 6,
  },
  metricDetail: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 5,
  },
  section: {
    backgroundColor: palette.panel,
    borderColor: palette.faint,
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
  },
  sectionEyebrow: {
    color: palette.red,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  sectionTitle: {
    color: palette.ink,
    fontSize: 20,
    fontWeight: '900',
    marginTop: 3,
  },
  sectionBody: {
    marginTop: 14,
  },
  searchInput: {
    backgroundColor: palette.panel,
    borderColor: palette.faint,
    borderRadius: 8,
    borderWidth: 1,
    color: palette.ink,
    fontSize: 15,
    fontWeight: '800',
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  segmentRow: {
    backgroundColor: palette.soft,
    borderColor: palette.faint,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 3,
  },
  segmentButton: {
    alignItems: 'center',
    borderRadius: 6,
    flex: 1,
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  segmentButtonActive: {
    backgroundColor: palette.panel,
  },
  segmentText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  segmentTextActive: {
    color: palette.ink,
  },
  rankList: {
    gap: 0,
  },
  companyRow: {
    alignItems: 'center',
    borderBottomColor: palette.faint,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 12,
  },
  companyRowExpanded: {
    backgroundColor: palette.soft,
    borderBottomWidth: 0,
    borderRadius: 8,
    marginHorizontal: -8,
    paddingHorizontal: 20,
  },
  expandIndicator: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 4,
  },
  companyDetails: {
    backgroundColor: palette.panel,
    borderBottomColor: palette.faint,
    borderBottomWidth: 1,
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  detailLabel: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: '700',
    flex: 1,
  },
  detailValue: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: '900',
    flex: 2,
    textAlign: 'right',
  },
  logoStack: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  companyLogo: {
    alignItems: 'center',
    backgroundColor: palette.soft,
    borderColor: palette.faint,
    borderRadius: 8,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 36,
  },
  companyLogoImage: {
    height: 36,
    width: 36,
  },
  companyLogoText: {
    color: palette.ink,
    fontSize: 12,
    fontWeight: '900',
  },
  rankBadge: {
    alignItems: 'center',
    backgroundColor: palette.soft,
    borderRadius: 8,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  rankBadgeText: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  companyMain: {
    flex: 1,
  },
  companyName: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  companyMeta: {
    color: palette.muted,
    fontSize: 12,
    marginTop: 4,
  },
  companyImpact: {
    alignItems: 'flex-end',
  },
  companyWorkers: {
    color: palette.red,
    fontSize: 16,
    fontWeight: '900',
  },
  companyWorkersLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  stockText: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: '900',
    marginTop: 4,
    maxWidth: 90,
  },
  stockUp: {
    color: palette.green,
  },
  stockDown: {
    color: palette.red,
  },
  emptyText: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  barList: {
    gap: 14,
  },
  barRow: {
    gap: 8,
  },
  barLabelRow: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  barLabel: {
    color: palette.ink,
    flex: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  barValue: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  barTrack: {
    backgroundColor: palette.soft,
    borderRadius: 8,
    height: 8,
    overflow: 'hidden',
  },
  barFill: {
    borderRadius: 8,
    height: 8,
  },
  horizontalBarList: {
    gap: 12,
    paddingRight: 16,
  },
  horizontalBarCard: {
    backgroundColor: palette.soft,
    borderColor: palette.faint,
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 160,
    padding: 12,
    width: 120,
  },
  horizontalBarLabel: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: '900',
    height: 36,
    lineHeight: 17,
  },
  horizontalBarValue: {
    color: palette.red,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 4,
  },
  horizontalBarSubtext: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: '700',
    marginTop: 2,
  },
  horizontalBarTrack: {
    alignItems: 'center',
    backgroundColor: palette.panel,
    borderRadius: 6,
    flex: 1,
    justifyContent: 'flex-end',
    marginTop: 12,
    overflow: 'hidden',
    width: '100%',
  },
  horizontalBarFill: {
    borderRadius: 6,
    width: '100%',
  },
  noticeRow: {
    alignItems: 'center',
    borderBottomColor: palette.faint,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 13,
  },
  noticeRowExpanded: {
    backgroundColor: palette.soft,
    borderBottomWidth: 0,
    borderRadius: 8,
    marginHorizontal: -8,
    paddingHorizontal: 20,
  },
  noticeDateBlock: {
    alignItems: 'center',
    backgroundColor: palette.soft,
    borderRadius: 8,
    minHeight: 46,
    justifyContent: 'center',
    width: 48,
  },
  noticeMonth: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  noticeDay: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: '900',
  },
  noticeMain: {
    flex: 1,
  },
  noticeCompany: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  noticeMeta: {
    color: palette.muted,
    fontSize: 12,
    marginTop: 4,
  },
  noticeImpact: {
    alignItems: 'flex-end',
  },
  noticeEmployees: {
    color: palette.red,
    fontSize: 16,
    fontWeight: '900',
  },
  noticeEmployeesLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  horizontalSectionsContainer: {
    gap: 12,
    paddingRight: 18,
  },
  horizontalSection: {
    backgroundColor: palette.panel,
    borderColor: palette.faint,
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
    width: 340,
  },
  horizontalSectionEyebrow: {
    color: palette.red,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  horizontalSectionTitle: {
    color: palette.ink,
    fontSize: 20,
    fontWeight: '900',
    marginTop: 3,
  },
  horizontalSectionBody: {
    marginTop: 14,
  },
  redditPostRow: {
    borderBottomColor: palette.faint,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 14,
  },
  redditPostRowExpanded: {
    backgroundColor: palette.soft,
    borderBottomWidth: 0,
    borderRadius: 8,
    marginHorizontal: -8,
    paddingHorizontal: 20,
  },
  redditPostHeader: {
    flex: 1,
    gap: 8,
  },
  redditMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  redditSubreddit: {
    color: palette.red,
    fontSize: 12,
    fontWeight: '900',
  },
  redditAuthor: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  redditDate: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: '600',
  },
  redditTitle: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 22,
  },
  companyTag: {
    alignSelf: 'flex-start',
    backgroundColor: palette.redSoft,
    borderColor: '#ffd1c5',
    borderRadius: 4,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  companyTagText: {
    color: palette.red,
    fontSize: 11,
    fontWeight: '900',
  },
  redditStats: {
    flexDirection: 'row',
    gap: 16,
  },
  redditScore: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  redditComments: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  redditPostDetails: {
    backgroundColor: palette.panel,
    borderBottomColor: palette.faint,
    borderBottomWidth: 1,
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  redditSelfText: {
    backgroundColor: palette.soft,
    borderRadius: 6,
    padding: 12,
  },
  redditSelfTextContent: {
    color: palette.ink,
    fontSize: 13,
    lineHeight: 19,
  },
  redditLinkButton: {
    alignItems: 'center',
    backgroundColor: palette.red,
    borderRadius: 8,
    marginTop: 8,
    paddingVertical: 12,
  },
  redditLinkButtonText: {
    color: palette.panel,
    fontSize: 14,
    fontWeight: '900',
  },
});
